name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (
        (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
        (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
        (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
        (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
      ) && (
        github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'MEMBER' ||
        github.event.comment.author_association == 'COLLABORATOR' ||
        github.event.review.author_association == 'OWNER' ||
        github.event.review.author_association == 'MEMBER' ||
        github.event.review.author_association == 'COLLABORATOR' ||
        github.event.issue.author_association == 'OWNER' ||
        github.event.issue.author_association == 'MEMBER' ||
        github.event.issue.author_association == 'COLLABORATOR'
      )
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      # オプション: セキュリティ強化（パブリックリポジトリ推奨）
      # - name: Harden runner environment
      #   uses: step-security/harden-runner@v2
      #   with:
      #     egress-policy: audit
      #     allowed-endpoints: >
      #       api.anthropic.com:443
      #       api.github.com:443
      #       github.com:443
      #       registry.npmjs.org:443

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # This is an optional setting that allows Claude to read CI results on PRs
          additional_permissions: |
            actions: read
          
          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4.1)
          # model: "claude-opus-4-1-20250805"
          
          # Optional: Customize the trigger phrase (default: @claude)
          # trigger_phrase: "/claude"
          
          # Optional: Trigger when specific user is assigned to an issue
          # assignee_trigger: "claude-bot"
          
          # Optional: Allow Claude to run specific commands
          allowed_tools: |
            Bash(pnpm *)
            Bash(git *)
            Bash(ls *)
            Bash(cat *)
            Bash(mkdir *)
            Bash(cp *)
            Bash(mv *)
            Bash(rm *)
            Bash(chmod *)
            Bash(find *)
            Bash(grep *)
            Edit
            Write
            Read
            Grep
            Glob
            LS
          
          custom_instructions: |
            ## セキュリティガイドライン
            - 既存のCLAUDE.mdファイルに従って作業する
            - 認証・認可に関わるコードは変更しない
            - .envファイルやシークレットにアクセスしない
            - 承認されていないパッケージをインストールしない
            - 外部APIコールは事前承認なしに行わない
            - プロジェクト範囲外のファイル削除・移動を行わない
            
            ## 開発ガイドライン  
            - TypeScriptを使用する
            - 新しいコードにはテストを追加する
            - pnpmを使用する（npmではない）
            - コーディング規約に従う
            - TDDスタイル（レッド→グリーン→リファクタリング）で進める
          
          # Optional: Custom environment variables for Claude
          # claude_env: |
          #   NODE_ENV: test

